name: "publish"
on:
  push:
    paths:
      - 'src-tauri/tauri.conf.json'
  workflow_dispatch:

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install app dependencies and build it
      run: pnpm install && pnpm run build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --bundles nsis
        tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "Activity tracker v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: false
        prerelease: false